name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"

    - name: Run unit tests
      run: pytest tests/ -v --tb=short -x

    - name: Run benchmarks (smoke test)
      run: |
        python -c "
        from benchmarks.benchmark_suite import run_benchmark, BENCHMARKS
        # Quick smoke test on easiest problem
        r = run_benchmark(BENCHMARKS[0], max_iterations=500, seed=42)
        print(f'Linear: R²={r[\"train_r2\"]:.4f}')
        assert r['train_r2'] > 0.9, f'Smoke test failed: R²={r[\"train_r2\"]}'
        "

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Check syntax
      run: python -m py_compile agi_composer/*.py
